### PR TITLE
Adding Ingress for ICMP to LB SG

### PR DESCRIPTION
**Pull request by gmhta**

### CODE REVIEW

**Review by paul-thompson-helix — COMMENTED** [review]
Where is load_balancer_security_group used? All projects and all load balancers? Why would all want to have icmp ingress?

**Comment by timbod7** [comment]
Seems harmless and useful to make load balancer pingable. 

@paul-thompson-helix can you see any risks with this?

**Comment by paul-thompson-helix** [comment]
More questions than risks.  

Adding a change like this to a widely shared resource will mean each project will come across this in their terraform plans and want to know what it is and why.
When deployed to something like Canva insights, Canva security engineers use tools to scan all of AWS and look at the ingress rules in detail and have recently asked us to justify ingress rules and tighten them down where possible.
So it's for those reasons that I ask why make this change.

Can onederful infra repo not simply make a security group as required for the purpose?
Or add in opt-in customisers or other params like we usually do in infrastructure shared changes?

Or one could say this is great because you can debug network connectivity issues with load balancers and you can use it to test x problem setting up internal load balancer.
So we learn what problem it solves and where it would be used.

**Comment by timbod7** [comment]
Given your concerns let's discuss on Wednesday

**Pull request closed without merging**
