### PR TITLE
add docker image options to lambda

### PR DESCRIPTION
**Pull request by jcalderin**

### CODE REVIEW

**Comment by jcalderin** [comment]
hx-terraform git:(feature/add_lambda_docker_options) ✗ dnit generate
... generateProviders
=== generateProviders
... generateTerraform
=== generateTerraform
--- generate

**Review by bacek — APPROVED** [review]
Squash and merge.

**Comment by jcalderin** [comment]
Had to do more modifications

**Comment by bacek** [comment]
Ship it.

**Comment by jcalderin** [comment]
A promise this is the last one, finally plan worked :)

**Comment by bacek** [comment]
SHIP IT!

**Pull request merged**
